// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcbdbqrvqkkfzgdbmdaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjYmRicXJ2cWtrZnpnZGJtZGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzAxODYsImV4cCI6MjA2NjgwNjE4Nn0.8LROgz6gn5Hy76QFWrO7xOEQwVlj9MEyD5rXTooRaAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});